name: fizzbuzz-olepunchy
region: sfo
services:
  - http_port: 80
    image:
      registry: olepunchy
      registry_type: DOCKER_HUB
      repository: fizzbuzz-mvc
      tag: "1.0.1"
    instance_count: 1
    instance_size_slug: basic-xxs
    name: fizzbuzz-olepunchy
    routes:
      - path: /
    source_dir: /
